### ISSUE TITLE
Adding Opml seems to crash the import process

### ISSUE THREAD

**Issue by gerroon** [akhilrex/podgrab#112]
*Before creating a bug report please make sure you are using the latest docker image / code base.*

**Please complete the following information**
 - Installation Type: Docker-compose

**Describe the bug**
Importing an OPML generated by AntennaPod causes partial imports with some segfault panic thing

See the log below

```
podgrab    | /assets/Blender Podcast
podgrab    | /assets/Blender Podcast/folder.png
podgrab    | /assets/LinuxServer-io
podgrab    | /assets/LinuxServer-io/folder.jpg
podgrab    | /assets/Darken the Page- Conversations about the Creative Process/folder.png
podgrab    | 
podgrab    | 2021/06/13 19:55:54 /api/db/dbfunctions.go:292
podgrab    | [2625.476ms] [rows:1] INSERT INTO `podcasts` (`id`,`created_at`,`updated_at`,`deleted_at`,`title`,`summary`,`author`,`image`,`url`,`last_episode`) VALUES ("3162911e-3d9e-4605-b1d3-392857d1ec37","2021-06-13 19:55:51.762","2021-06-13 19:55:51.762",NULL,"Escape From Illustration Island","Escape From Illustration Island is the critically-acclaimed audio podcast featuring conversations with Illustrators, Art Directors, Art Reps and other creative professionals. Past guests include Drew Struzan, Christoph Niemann, Marshall Arisman, Gary Taxali, Bob Staake and more.    Visit IllustrationAge.com for the ultimate resources for Illustrators!","illustrationisland","https://show-profile-images.s3.amazonaws.com/production/1345/escape-from-illustration-island_1531860873_itunes.png","https://www.talkshoe.com/rss-escape-from-illustration-island.xml",NULL)
podgrab    | /assets/Escape From Illustration Island
podgrab    | /assets/Escape From Illustration Island/folder.png
podgrab    | Response status: 200 OK
podgrab    | Response status: 200 OK
podgrab    | Response status: 200 OK
podgrab    | Response status: 200 OK
podgrab    | Response status: 200 OK
podgrab    | Response status: 200 OK
podgrab    | Response status: 200 OK
podgrab    | Response status: 200 OK
podgrab    | Response status: 200 OK
podgrab    | Response status: 200 OK
podgrab    | Response status: 200 OK
podgrab    | Response status: 200 OK
podgrab    | Response status: 200 OK
podgrab    | Response status: 200 OK
podgrab    | Response status: 200 OK
podgrab    | Response status: 200 OK
podgrab    | Response status: 200 OK
podgrab    | panic: runtime error: invalid memory address or nil pointer dereference
podgrab    | [signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0x9052aa]
podgrab    | 
podgrab    | goroutine 100 [running]:
podgrab    | github.com/akhilrex/podgrab/service.getItunesImageUrl(0xc0022e0000, 0x33f33, 0x3fe00, 0x0, 0xc0004421b3)
podgrab    |    /api/service/podcastService.go:188 +0x12a
podgrab    | github.com/akhilrex/podgrab/service.AddPodcast(0xc0001127e0, 0x2e, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
podgrab    |    /api/service/podcastService.go:219 +0x5ea
podgrab    | github.com/akhilrex/podgrab/service.AddOpml.func1(0xc00020d180, 0xc0001127e0, 0x2e)
podgrab    |    /api/service/podcastService.go:123 +0x8a
podgrab    | created by github.com/akhilrex/podgrab/service.AddOpml
podgrab    |    /api/service/podcastService.go:121 +0x3fb



```

**Comment by akhilrex** [comment]
Can you please attach the opml.

Thanks and Regards

Akhil Gupta

**Comment by akhilrex** [comment]
Hi

Can you please attach the OPML?

**Comment by gerroon** [comment]
Hi

Sorry I need to give you a sample of the OPML  since the whole thing is a b it personal.

**Comment by akhilrex** [comment]
I dont think a sample OPML would work but I will give it a try.

**Comment by akhilrex** [comment]
I could not replicate the issue. Please repopen if you feel you can share the relevant file.
